### ISSUE TITLE
About structure of OAD dataset

### ISSUE THREAD

**Issue by giangnd1808** [DelamareMicka/SW-GCN#2]
Can you provide example about 1 sample of skeleton data and anotation file ? Because OAD is too large for me to download ( 50GB with zip file ). I can't imagine structure folder of this dataset, and i want to use UOW online instead . Thank you so much.

**Comment by giangnd1808** [comment]
Thank you. I've downloaded the data

**Comment by DelamareMicka** [comment]
Hello,

Okay, if you need some help don't hesitate, I know it's not simple

Best regards,
